### ISSUE TITLE
Inquiry about Supporting KFX format

### ISSUE THREAD

**Issue by SV-stark** [acamposcar/kindle-calibre-bot#1]
Are there any plans to add support for conversion to/ from KFX format ? (it has better compatibility with kindle devices), There isone other telegram bot that can do it (it's also on github).

**Comment by acamposcar** [comment]
I can check if it is possible but I don't have any KFX file. Can you send me a KFX file to test it? 
Send it to kindlesendbot@gmail.com or send me a link to download it

**Comment by SV-stark** [comment]
sure, i will email you both epub and kfx of a file so you can test and compare.
