### ISSUE TITLE
Book title error

### ISSUE THREAD

**Issue by daybreak-git** [acamposcar/kindle-calibre-bot#2]
As of May 2022 email push no longer accepts .mobi format, I changed line 56 in the bot.py code to .epub
Another thing is that the email name given by kindle ends with .cn, not .com anymore, I changed line 185 to .com
Now there is another problem I can't solve is that the attachment sent by email is noname without any formatting or book title, can you tell me where it needs to be changed?
![image](https://user-images.githubusercontent.com/74316793/216744005-087087b8-c6e1-431c-94ef-35a5ecf1332d.png)

**Comment by acamposcar** [comment]
Fixed
