### ISSUE TITLE
Accented character result in empty file

### ISSUE THREAD

**Issue by twisterrm** [acamposcar/kindle-calibre-bot#3]
Hi, i have an issue with the bot.
I changed the default from .mobi to .epub due to new amazon changes withiut issue.
If the ebook have an accented character (like "Verità.epub") the mail sent result with a "no name" file attached and obv kindle not receiving it

**Comment by daybreak-git** [comment]
Have you solved it? I'm also having problems sending files without names

**Comment by twisterrm** [comment]
Sorry for the late answer, i figured out 
in line 28 of src/gmail.py 
change 
`part = MIMEBase("application", "octet-stream")`
to
`part = MIMEBase("application", "octet-stream", Name=file)`

**Comment by acamposcar** [comment]
Fixed
